### PR TITLE
Add --ignore-gitattr to ignore .gitattributes

### PR DESCRIPTION
**Pull request by insilications**
Add --ignore-gitattr to fully ignore .gitattributes files. Specific tests need to be added.

### CODE REVIEW

**Comment by Kentzo** [comment]
What other git attributes are you trying to ignore?

**Comment by insilications** [comment]
> What other git attributes are you trying to ignore?

https://github.com/google/brotli/blob/master/.gitattributes

I was having a hard time using git-archive-all and forcing to pull the submodules as well.

**Comment by Kentzo** [comment]
Hmm, could you detail the expected and actual behavior regarding the export-ignore attribute? 

Best Regards
Ilya Kulakov

**Comment by Kentzo** [comment]
The `--no-exclude` CLI option was ignored. Please try to fix I just pushed.

**Comment by insilications** [comment]
> The `--no-exclude` CLI option was ignored. Please try the fix that I just pushed.

Tried the fix. It works perfectly now and renders my solution useless.

**Pull request closed without merging**
