### PR TITLE
topless option - when packing, don't add another hierarchy on top

### PR DESCRIPTION
**Pull request by vim-zz**

### CODE REVIEW

**Comment by Kentzo** [comment]
@vim-zz Thanks for the PR!

May I ask for a description of this feature with an example?

**Comment by vim-zz** [comment]
using topless option creates the archive without adding a top directory inside the archive.

example, having the following directory tree:
a/
b/
c/

normally will create archive which when expanded will look like:
tag-name/
    a/
    b/
    c/

when using topless option the result will look like this:
a/
b/
c/

**Comment by Kentzo** [comment]
@vim-zz Isn't it the same as `--prefix=''` ?

**Comment by vim-zz** [comment]
you are correct, its the same, i missed that option...

**Comment by vim-zz** [comment]
abort! 
:-)

**Pull request closed without merging**
